name: Production workflow

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Use Node.js 18.x
              uses: actions/setup-node@v1
              with:
                  node-version: 18.x
            - run: npm install
            - run: npm run build --if-present
            - name: Deploy to Heroku
              uses: akhileshns/heroku-deploy@v3.12.14
              with:
                  heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
                  heroku_app_name: "react-metronome-prod"
                  heroku_email: "lt6363185@gmail.com"
